services:
  gateway:
    network_mode: host
    ports: !override []
    environment:
      CONFIG_PATH: /etc/gateway/gateway.toml
      RUST_LOG: info

  mock-provider-1:
    network_mode: host
    environment:
      PORT: "9001"
      RUST_LOG: info

  mock-provider-2:
    network_mode: host
    environment:
      PORT: "9002"
      RUST_LOG: info

  postgres:
    network_mode: host
    ports: !override []

  redis:
    network_mode: host
    ports: !override []

  otel-collector:
    network_mode: host

  prometheus:
    network_mode: host
    ports: !override []

  grafana:
    network_mode: host
    ports: !override []
